// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/starlink.proto

package starlink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for satellite status
type SatelliteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteRequest) Reset() {
	*x = SatelliteRequest{}
	mi := &file_proto_starlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteRequest) ProtoMessage() {}

func (x *SatelliteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteRequest.ProtoReflect.Descriptor instead.
func (*SatelliteRequest) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

// Response message for satellite status
type SatelliteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteResponse) Reset() {
	*x = SatelliteResponse{}
	mi := &file_proto_starlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteResponse) ProtoMessage() {}

func (x *SatelliteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteResponse.ProtoReflect.Descriptor instead.
func (*SatelliteResponse) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{1}
}

func (x *SatelliteResponse) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *SatelliteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SatelliteResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SatelliteResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SatelliteResponse) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *SatelliteResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request message for configuration update
type ConfigUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateRequest) Reset() {
	*x = ConfigUpdateRequest{}
	mi := &file_proto_starlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateRequest) ProtoMessage() {}

func (x *ConfigUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateRequest.ProtoReflect.Descriptor instead.
func (*ConfigUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdateRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *ConfigUpdateRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// Response message for configuration update
type ConfigUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateResponse) Reset() {
	*x = ConfigUpdateResponse{}
	mi := &file_proto_starlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateResponse) ProtoMessage() {}

func (x *ConfigUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateResponse.ProtoReflect.Descriptor instead.
func (*ConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for telemetry stream
type TelemetryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId     string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_starlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *TelemetryRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// Telemetry data message
type TelemetryData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId    string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Temperature    float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	PowerLevel     float64                `protobuf:"fixed64,3,opt,name=power_level,json=powerLevel,proto3" json:"power_level,omitempty"`
	SignalStrength string                 `protobuf:"bytes,4,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_proto_starlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_starlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_proto_starlink_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryData) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *TelemetryData) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TelemetryData) GetPowerLevel() float64 {
	if x != nil {
		return x.PowerLevel
	}
	return 0
}

func (x *TelemetryData) GetSignalStrength() string {
	if x != nil {
		return x.SignalStrength
	}
	return ""
}

func (x *TelemetryData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_starlink_proto protoreflect.FileDescriptor

const file_proto_starlink_proto_rawDesc = "" +
	"\n" +
	"\x14proto/starlink.proto\x12\bstarlink\"5\n" +
	"\x10SatelliteRequest\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\"\xc2\x01\n" +
	"\x11SatelliteResponse\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x01R\baltitude\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xb6\x01\n" +
	"\x13ConfigUpdateRequest\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12A\n" +
	"\x06config\x18\x02 \x03(\v2).starlink.ConfigUpdateRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x14ConfigUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x10TelemetryRequest\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"\xbc\x01\n" +
	"\rTelemetryData\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1f\n" +
	"\vpower_level\x18\x03 \x01(\x01R\n" +
	"powerLevel\x12'\n" +
	"\x0fsignal_strength\x18\x04 \x01(\tR\x0esignalStrength\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\x82\x02\n" +
	"\x0fStarlinkControl\x12M\n" +
	"\x12GetSatelliteStatus\x12\x1a.starlink.SatelliteRequest\x1a\x1b.starlink.SatelliteResponse\x12V\n" +
	"\x15UpdateSatelliteConfig\x12\x1d.starlink.ConfigUpdateRequest\x1a\x1e.starlink.ConfigUpdateResponse\x12H\n" +
	"\x0fStreamTelemetry\x12\x1a.starlink.TelemetryRequest\x1a\x17.starlink.TelemetryData0\x01B\"Z starlink-cntrl-grpc/pkg/starlinkb\x06proto3"

var (
	file_proto_starlink_proto_rawDescOnce sync.Once
	file_proto_starlink_proto_rawDescData []byte
)

func file_proto_starlink_proto_rawDescGZIP() []byte {
	file_proto_starlink_proto_rawDescOnce.Do(func() {
		file_proto_starlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_starlink_proto_rawDesc), len(file_proto_starlink_proto_rawDesc)))
	})
	return file_proto_starlink_proto_rawDescData
}

var file_proto_starlink_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_starlink_proto_goTypes = []any{
	(*SatelliteRequest)(nil),     // 0: starlink.SatelliteRequest
	(*SatelliteResponse)(nil),    // 1: starlink.SatelliteResponse
	(*ConfigUpdateRequest)(nil),  // 2: starlink.ConfigUpdateRequest
	(*ConfigUpdateResponse)(nil), // 3: starlink.ConfigUpdateResponse
	(*TelemetryRequest)(nil),     // 4: starlink.TelemetryRequest
	(*TelemetryData)(nil),        // 5: starlink.TelemetryData
	nil,                          // 6: starlink.ConfigUpdateRequest.ConfigEntry
}
var file_proto_starlink_proto_depIdxs = []int32{
	6, // 0: starlink.ConfigUpdateRequest.config:type_name -> starlink.ConfigUpdateRequest.ConfigEntry
	0, // 1: starlink.StarlinkControl.GetSatelliteStatus:input_type -> starlink.SatelliteRequest
	2, // 2: starlink.StarlinkControl.UpdateSatelliteConfig:input_type -> starlink.ConfigUpdateRequest
	4, // 3: starlink.StarlinkControl.StreamTelemetry:input_type -> starlink.TelemetryRequest
	1, // 4: starlink.StarlinkControl.GetSatelliteStatus:output_type -> starlink.SatelliteResponse
	3, // 5: starlink.StarlinkControl.UpdateSatelliteConfig:output_type -> starlink.ConfigUpdateResponse
	5, // 6: starlink.StarlinkControl.StreamTelemetry:output_type -> starlink.TelemetryData
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_starlink_proto_init() }
func file_proto_starlink_proto_init() {
	if File_proto_starlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_starlink_proto_rawDesc), len(file_proto_starlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_starlink_proto_goTypes,
		DependencyIndexes: file_proto_starlink_proto_depIdxs,
		MessageInfos:      file_proto_starlink_proto_msgTypes,
	}.Build()
	File_proto_starlink_proto = out.File
	file_proto_starlink_proto_goTypes = nil
	file_proto_starlink_proto_depIdxs = nil
}
