// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/starlink.proto

package starlink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StarlinkControl_GetSatelliteStatus_FullMethodName    = "/starlink.StarlinkControl/GetSatelliteStatus"
	StarlinkControl_UpdateSatelliteConfig_FullMethodName = "/starlink.StarlinkControl/UpdateSatelliteConfig"
	StarlinkControl_StreamTelemetry_FullMethodName       = "/starlink.StarlinkControl/StreamTelemetry"
)

// StarlinkControlClient is the client API for StarlinkControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Starlink Control Service
type StarlinkControlClient interface {
	// Get satellite status
	GetSatelliteStatus(ctx context.Context, in *SatelliteRequest, opts ...grpc.CallOption) (*SatelliteResponse, error)
	// Update satellite configuration
	UpdateSatelliteConfig(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error)
	// Stream telemetry data
	StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryData], error)
}

type starlinkControlClient struct {
	cc grpc.ClientConnInterface
}

func NewStarlinkControlClient(cc grpc.ClientConnInterface) StarlinkControlClient {
	return &starlinkControlClient{cc}
}

func (c *starlinkControlClient) GetSatelliteStatus(ctx context.Context, in *SatelliteRequest, opts ...grpc.CallOption) (*SatelliteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SatelliteResponse)
	err := c.cc.Invoke(ctx, StarlinkControl_GetSatelliteStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starlinkControlClient) UpdateSatelliteConfig(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigUpdateResponse)
	err := c.cc.Invoke(ctx, StarlinkControl_UpdateSatelliteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starlinkControlClient) StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StarlinkControl_ServiceDesc.Streams[0], StarlinkControl_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetryData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StarlinkControl_StreamTelemetryClient = grpc.ServerStreamingClient[TelemetryData]

// StarlinkControlServer is the server API for StarlinkControl service.
// All implementations must embed UnimplementedStarlinkControlServer
// for forward compatibility.
//
// Starlink Control Service
type StarlinkControlServer interface {
	// Get satellite status
	GetSatelliteStatus(context.Context, *SatelliteRequest) (*SatelliteResponse, error)
	// Update satellite configuration
	UpdateSatelliteConfig(context.Context, *ConfigUpdateRequest) (*ConfigUpdateResponse, error)
	// Stream telemetry data
	StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryData]) error
	mustEmbedUnimplementedStarlinkControlServer()
}

// UnimplementedStarlinkControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStarlinkControlServer struct{}

func (UnimplementedStarlinkControlServer) GetSatelliteStatus(context.Context, *SatelliteRequest) (*SatelliteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSatelliteStatus not implemented")
}
func (UnimplementedStarlinkControlServer) UpdateSatelliteConfig(context.Context, *ConfigUpdateRequest) (*ConfigUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSatelliteConfig not implemented")
}
func (UnimplementedStarlinkControlServer) StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryData]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedStarlinkControlServer) mustEmbedUnimplementedStarlinkControlServer() {}
func (UnimplementedStarlinkControlServer) testEmbeddedByValue()                         {}

// UnsafeStarlinkControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarlinkControlServer will
// result in compilation errors.
type UnsafeStarlinkControlServer interface {
	mustEmbedUnimplementedStarlinkControlServer()
}

func RegisterStarlinkControlServer(s grpc.ServiceRegistrar, srv StarlinkControlServer) {
	// If the following call pancis, it indicates UnimplementedStarlinkControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StarlinkControl_ServiceDesc, srv)
}

func _StarlinkControl_GetSatelliteStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatelliteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarlinkControlServer).GetSatelliteStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarlinkControl_GetSatelliteStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarlinkControlServer).GetSatelliteStatus(ctx, req.(*SatelliteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarlinkControl_UpdateSatelliteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarlinkControlServer).UpdateSatelliteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarlinkControl_UpdateSatelliteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarlinkControlServer).UpdateSatelliteConfig(ctx, req.(*ConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarlinkControl_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StarlinkControlServer).StreamTelemetry(m, &grpc.GenericServerStream[TelemetryRequest, TelemetryData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StarlinkControl_StreamTelemetryServer = grpc.ServerStreamingServer[TelemetryData]

// StarlinkControl_ServiceDesc is the grpc.ServiceDesc for StarlinkControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarlinkControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "starlink.StarlinkControl",
	HandlerType: (*StarlinkControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSatelliteStatus",
			Handler:    _StarlinkControl_GetSatelliteStatus_Handler,
		},
		{
			MethodName: "UpdateSatelliteConfig",
			Handler:    _StarlinkControl_UpdateSatelliteConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _StarlinkControl_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/starlink.proto",
}
