# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: starlink.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'starlink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estarlink.proto\x12\x11SpaceX.API.Device\"\x9a\x01\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12:\n\nget_status\x18\xec\x07 \x01(\x0b\x32#.SpaceX.API.Device.GetStatusRequestH\x00\x12<\n\x0bget_history\x18\xed\x07 \x01(\x0b\x32$.SpaceX.API.Device.GetHistoryRequestH\x00\x42\t\n\x07request\"\x9e\x01\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\x04\x12;\n\nget_status\x18\xec\x07 \x01(\x0b\x32$.SpaceX.API.Device.GetStatusResponseH\x00\x12=\n\x0bget_history\x18\xed\x07 \x01(\x0b\x32%.SpaceX.API.Device.GetHistoryResponseH\x00\x42\n\n\x08response\"\x12\n\x10GetStatusRequest\"}\n\x11GetStatusResponse\x12\x32\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x1d.SpaceX.API.Device.DeviceInfo\x12\x34\n\x0c\x64\x65vice_state\x18\x02 \x01(\x0b\x32\x1e.SpaceX.API.Device.DeviceState\"x\n\nDeviceInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10hardware_version\x18\x02 \x01(\t\x12\x18\n\x10software_version\x18\x03 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x04 \x01(\t\x12\x14\n\x0cutc_offset_s\x18\x05 \x01(\x05\"\x1f\n\x0b\x44\x65viceState\x12\x10\n\x08uptime_s\x18\x01 \x01(\x01\"\x13\n\x11GetHistoryRequest\"\xa7\x01\n\x12GetHistoryResponse\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\x04\x12\x1b\n\x12pop_ping_drop_rate\x18\xe9\x07 \x03(\x02\x12\x1c\n\x13pop_ping_latency_ms\x18\xea\x07 \x03(\x02\x12 \n\x17\x64ownlink_throughput_bps\x18\xeb\x07 \x03(\x02\x12\x1e\n\x15uplink_throughput_bps\x18\xec\x07 \x03(\x02\x32K\n\x06\x44\x65vice\x12\x41\n\x06Handle\x12\x1a.SpaceX.API.Device.Request\x1a\x1b.SpaceX.API.Device.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'starlink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=192
  _globals['_RESPONSE']._serialized_start=195
  _globals['_RESPONSE']._serialized_end=353
  _globals['_GETSTATUSREQUEST']._serialized_start=355
  _globals['_GETSTATUSREQUEST']._serialized_end=373
  _globals['_GETSTATUSRESPONSE']._serialized_start=375
  _globals['_GETSTATUSRESPONSE']._serialized_end=500
  _globals['_DEVICEINFO']._serialized_start=502
  _globals['_DEVICEINFO']._serialized_end=622
  _globals['_DEVICESTATE']._serialized_start=624
  _globals['_DEVICESTATE']._serialized_end=655
  _globals['_GETHISTORYREQUEST']._serialized_start=657
  _globals['_GETHISTORYREQUEST']._serialized_end=676
  _globals['_GETHISTORYRESPONSE']._serialized_start=679
  _globals['_GETHISTORYRESPONSE']._serialized_end=846
  _globals['_DEVICE']._serialized_start=848
  _globals['_DEVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
